### ISSUE TITLE
`fs_more::directory::copy_directory` mishandles relative symlinks

### ISSUE THREAD

**Issue by cyqsimon** [simongoricar/fs-more#3]
## Description

When a source directory contains a relative symlink, `copy_directory` copies it as is even with `SymlinkBehaviour::Follow` set.

## MRE

```rust
use std::{fs, os::unix::fs::symlink};

use fs_more::directory::{DirectoryCopyOptions, SymlinkBehaviour};

fn main() -> anyhow::Result<()> {
    // Setup the following file tree:
    // test/
    // └── source/
    //     ├── linked
    //     └── symlink-source/
    //         └── link -> ../linked
    fs::create_dir_all("test/source/symlink-source/")?;
    fs::write("test/source/linked", "")?;
    symlink("../linked", "test/source/symlink-source/link")?;

    // Copy using `cp -rL test/source/symlink-source/ test/dest/`:
    // test/
    // ├── dest/
    // │   └── link
    // └── source/
    //     ├── linked
    //     └── symlink-source/
    //         └── link -> ../linked

    // Copy using `fs_more`:
    // Notice how `test/dest/link` is not a regular file but a broken link.
    // test/
    // ├── dest/
    // │   └── link -> ../linked
    // └── source/
    //     ├── linked
    //     └── symlink-source/
    //         └── link -> ../linked
    let copy_options = DirectoryCopyOptions {
        symlink_behaviour: SymlinkBehaviour::Follow,
        ..Default::default()
    };
    fs_more::directory::copy_directory("test/source/symlink-source/", "test/dest/", copy_options)?;

    Ok(())
}
```

**Comment by simongoricar** [comment]
Thank you for the report, I would have thought the tests covered this, but clearly not. Will have a look at this in the following days when I get the chance. 

Given your wording, I assume this does not happen on absolute symlinks?

**Comment by cyqsimon** [comment]
> Given your wording, I assume this does not happen on absolute symlinks?

Correct. Absolute symlinks seem fine in my usage.

**Comment by simongoricar** [comment]
Turns out that the copy planner did not have any special handling for relative symlinks. It would try to check whether the destination exists relative to the current directory (and not relative to the symlink). In turn, that meant it would think the symlink destination doesn't exist, and it classified relative symlinks as broken ones.

I've added test cases covering this in https://github.com/simongoricar/fs-more/commit/5715999c475740621d09372621fac3bb78aa8ee3 and the fix in https://github.com/simongoricar/fs-more/commit/d1b52fca3e5997c9f7461912ab033eefc7841b0d. I'll make a `0.8.0` release shortly.

**Comment by simongoricar** [comment]
Alright, `0.8.0` is out on crates.io. Thanks for the report :)

**Comment by cyqsimon** [comment]
> Turns out that the copy planner did not have any special handling for relative symlinks. It would try to check whether the destination exists relative to the current directory (and not relative to the symlink). In turn, that meant it would think the symlink destination doesn't exist, and it classified relative symlinks as broken ones.

Yeah that lines up with my suspicion too.

> Alright, `0.8.0` is out on crates.io. Thanks for the report :)

And thank you for the swift fix!
